### ISSUE TITLE
"Enter" command doesn't register when searching in search bar

### ISSUE THREAD

**Issue by akwio** [Appleseed/leaves.topic#5]
Desc: When the user types a term to search in the search bar, nothing happens when they press "Enter". 
AC: When the user presses "enter" on the keyboard the phrase they typed should be searched. 

https://www.screenmailer.com/v/fv140GP2UbyaJ6k

**Comment by mddanishyusuf** [comment]
@akwio if user type whatever and that keyword not matched with wallabag tags then there is no result found. https://www.screenmailer.com/v/oH1I43WqAZiCaOs

**Comment by SinghPrakash0206** [comment]
This was not an issue but a limitation on better user experience. We will try to make this more user-friendly in our future release.
