### ISSUE TITLE
Can't Add a leaf when viewing tags. 

### ISSUE THREAD

**Issue by akwio** [Appleseed/leaves.topic#6]
DES: When the user is on the tags page and tries to add a leaf. The add popup appears behind the page of tags. This means that the user can't add any leaves until the tags are closed. 

AC: When the user is on the tags page, they should be able to add leaves without leaving the tag page. Furthermore, users should be able to add leaves no matter what page they are on. This will be better for the user experience. 

https://www.screenmailer.com/v/ZMbbauvsa0aS4AM

**Comment by mddanishyusuf** [comment]
@akwio plz test dev envirement https://www.screenmailer.com/v/qAfTZLwYuOmaJiA

**Comment by SinghPrakash0206** [comment]
The issue is not fixed.
